In [4]:
import numpy as np

import config
from config import Positions, Dims
from src.interfaces.pose import Pose, Position
import matplotlib.pyplot as plt

In [5]:
position = Position(Positions.ready2)

#print("\nlocal\n", position.local)
print("\nworld\n", position.world)

rotated = position.rotated(10)
#print("\nrotated local\n", rotated.local)
print("\nrotated world\n", rotated.world)

print("\noffsets\n", rotated.world-position.world)




world
 [[ 146.    76.   129.6]
 [ 146.   -76.   129.6]
 [-146.   -76.   129.6]
 [-146.    76.   129.6]]

rotated world
 [[ 130.58467044  100.19802317  129.6       ]
 [ 156.97919344  -49.49275529  129.6       ]
 [-130.58467044 -100.19802317  129.6       ]
 [-156.97919344   49.49275529  129.6       ]]

offsets
 [[-15.41532956  24.19802317   0.        ]
 [ 10.97919344  26.50724471   0.        ]
 [ 15.41532956 -24.19802317   0.        ]
 [-10.97919344 -26.50724471   0.        ]]


In [6]:
position.local * config.FLIP

array([[  20. ,    5. ,  129.6],
       [ -20. ,   -5. , -129.6],
       [ -20. ,   -5. , -129.6],
       [  20. ,    5. ,  129.6]])